filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  indices:
    - index: "ftgo-logs-%{+yyyy.MM.dd}"

setup.template:
  name: "ftgo-logs"
  pattern: "ftgo-logs-*"
setup.ilm.enabled: false
setup.kibana:
  host: "http://kibana:5601"
